# Generated by Django 2.2.6 on 2019-10-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daisy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestBook',
        ),
    ]
